services:
  - type: web
    name: conversor-catalogo
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 600 --max-requests 15 --max-requests-jitter 5
